# Mining waste database

Explore the mining waste database accross Canada built from Google Earth satellite imagery. The mining sites have been identified from the **Global Tailings Portal** and several other sources including **Canadian National Pollutant Release Inventory (NPRI)**, **United States Geological Survey (USGS)** and **International Commission on Large Dams (ICOLD)** databases.

In [20]:
import pandas as pd
url='https://raw.githubusercontent.com/AdriDim/review2022/main/database_mining_waste_canada.csv'

df = pd.read_csv(url, skiprows=0, sep=';')

        id      latitude    longitude  TSF(ha)  WRP(ha)  PIT(ha)  TOT(ha) PROV
0    #2400  -67,13699976  45,16139621        0        0       41       41   NB
1    #2402  -67,04130379   45,8488465       20        0        0       20   NB
2    #2408  -65,87768215  47,08589363        0      151        0      151   NB
3    #2409  -66,07114002  47,27611075      334        0        0      334   NB
4    #2410  -65,87040423   47,4783789      704        0        0      704   NB
..     ...           ...          ...      ...      ...      ...      ...  ...
396  #3019  -81,34679048  46,43002099        0       30       10       40   ON
397  #3020  -80,23170985  44,14194054        0        0       80       80   ON
398  #3021  -79,98659829  43,84865891        0        0      830      830   ON
399  #3022  -80,00235596  43,61786634        0        0      169      169   ON
400  #3023  -80,14606408  43,80892279        0        0       68       68   ON

[401 rows x 8 columns]

In [ ]:
df